(source gnu)
(source marmalade)
(source melpa)

(depends-on "cask")
(depends-on "flycheck")
(depends-on "gist")
(depends-on "git-gutter")
(depends-on "magit")
(depends-on "mo-git-blame")
(depends-on "pallet")
(depends-on "php-mode")
(depends-on "scala-mode2")
(depends-on "web-mode")
(depends-on "zenburn-theme")
